### ISSUE TITLE
测试用例是不是写错了？

### ISSUE THREAD

**Issue by little-dawenhing** [HuangRunHua/wwdc23-code-notes#1]
final class struct_initial_macroTests: XCTestCase {
    func testMacro() {
        assertMacroExpansion(
            """
            @StructInit
            struct Book {
                var id: Int
                var title: String
                var subtitle: String
                var description: String
                var author: String
              	init(id: Int, title: String, subtitle: String, description: String, author: String) {
                    self.id = id
                    self.title = title
                    self.subtitle = subtitle
                    self.description = description
                    self.author = author
                }
            }
            """,
            expandedSource:
            """
            
            struct Book {
                var id: Int
                var title: String
                var subtitle: String
                var description: String
                var author: String
                init(id: Int, title: String, subtitle: String, description: String, author: String) {
                    self.id = id
                    self.title = title
                    self.subtitle = subtitle
                    self.description = description
                    self.author = author
                }
            }
            """,
            macros: testMacros
        )
    }
}

**Comment by HuangRunHua** [comment]
你指的是哪里的示例？**Code**里面的还是**README**里面的
