### ISSUE TITLE
Why the test fail for macro?

### ISSUE THREAD

**Issue by shamiul110107** [HuangRunHua/wwdc23-code-notes#4]
<img width="652" alt="Screenshot 2023-10-08 at 15 26 28" src="https://github.com/HuangRunHua/wwdc23-code-notes/assets/11335997/79f13224-a763-4861-a79d-011a7f34c46a">

**Comment by HuangRunHua** [comment]
Hi there, have you notice that there is a space at the bottom of the “Actual expanded source:” line? Is it the space you added in test code or the Xcode generated? If it is added by you please remove it.Sent from my iPhoneOn Oct 8, 2023, at 16:27, Md. Shamiul Islam ***@***.***> wrote:﻿

**Comment by shamiul110107** [comment]
Now I have added new line after variable declaration then write the init method. Now test passed. 
Thanks
